### ISSUE TITLE
Goal Schema Review and Discussion

### ISSUE THREAD

**Issue by bchehraz** [chingu-voyages/v22-bears-team-05#1]
Hi Tom I thought I would review your goal schema so far, 

File in question: https://github.com/chingu-voyages/v22-bears-team-05/blob/master/server/models/Goal.js

You were on the right track so far in the goal schema. You referenced the `User` correctly.
```
user: {
    type: Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
```
However the way that you reference the taskSchema in an array within the goalSchema is not the way to go about this data model (and same for subtask within task)

If we're going to have a Goal, Task, and Subtask datatype, they need to all be each their own schema for MongoDB to be able to create a document for each.

So instead of exporting only the Goal schema, need to export all 3... Ideally in separate files for readability.
```
module.exports = model("Goal", goalSchema);
module.exports = model("Task", taskSchema);
module.exports = model("Subtask", subtaskSchema);
```

Now the way that you're supposed to reference the Task array inside Goal, as well as Subtask array inside Task, here's how you would do that:
`goalSchema`
```
tasks: [{
  type: Schema.Types.ObjectId,
  ref: "Task",
}]
```
and similarly for `taskSchema`:
```
subtasks: [{
  type: Schema.Types.ObjectId,
  ref: "Subtask",
}]
```

Beyond that, as far as the scope goes for Sprint 1, I think this is solid. All you have is fill out the type definitions in typeDefs.js for GraphQL to recognize these types (which by the way it's easier to do them in GraphQL first and then create the MongoDB model for them). And if you plan to do the GraphQL portion, just know that there is no `Date` type in GraphQL so you can use String instead. Or the other way to go about it is creating a custom Scalar type for Date but this is a more complicated route.

### Questions for future sprints regarding these data models:

1) Should we delete Subtasks upon completing them? What about Tasks?

If we plan to delete them, then there's no reason to keep around the "timeCompleted" or "isCompleted" and would instead add these up to a Goal's # of tasks completed + time spent on achieving a goal. And same thing could apply to a Task with total number of subtasks completed or total time spent on a task with subtasks included.

2) Should subtasks just be tasks that reference themselves? In other words, a Task can have an array of subtasks which reference other Task objects, instead of having another document for subtasks... this could allow for higher depth of tasks. Just a thought.

This is open to discussion, we should continue to think about how tasks and subtasks should be handled on the backend.

**Comment by tdepasquale** [comment]
Hi Bob, thanks for reviewing it! 

I'm a bit confused though haha. Why is it not the way to go about this data model? I wasn't referencing tasks and subtasks, I just made them subdocuments.

Here it is in the documentation https://mongoosejs.com/docs/subdocs.html

This way 1 goal document contains all of the information about a goal, including the tasks and subtasks. Is there a reason that it is important for us to create a new document for each task and subtask, then reference them instead of just embedding it all in one goal document like this?

**Comment by AnimeshKC** [comment]
I imagine referencing would be better for the future features. Eventually, the user should have the freedom to create a subtask (perhaps mini-task is a better word here) without being assigned to a goal or task. And referencing might also make it easier to change what goal a task or mini-task is part of, as a user may decide that a task belongs to a different goal. 

Separating the schemas seems better to build with extendability in mind. It probably won’t take much effort to do this from the get-go, and changing it in the future might possibly require us to change other parts of our app that involve goals.

**Comment by AnimeshKC** [comment]
“ Should subtasks just be tasks that reference themselves? In other words, a Task can have an array of subtasks which reference other Task objects, instead of having another document for subtasks... this could allow for higher depth of tasks. Just a thought.”

This could be an interesting approach, but we may need to think about our time logging system when deciding this. We’ll probably have a page that displays the user’s time spent, separated in days.

I was thinking the time page  has an entry per day and stores mini-tasks which have  properties that specify what task and/or goal it belongs to, if any. If we make tasks just a nested chain instead of having mini-tasks and task containers, it might make our time visualization more difficult, unless we come up with a particular scheme to make that work better. 


“Should we delete Subtasks upon completing them? What about Tasks?
If we plan to delete them, then there's no reason to keep around the "timeCompleted" or "isCompleted" and would instead add these up to a Goal's # of tasks completed + time spent on achieving a goal. And same thing could apply to a Task with total number of subtasks completed or total time spent on a task with subtasks included.”

This will likely depend on how we’re handling time visualization: what kind of entries we’re visualizing, i.e. are we only visualizing goals or are we visualizing individual mini-tasks; and how far we’re letting the user see (i.e. only the past week of time data, or the past month, or the past year). It could be possible that once we delete a mini-task, it can be removed from the database, but we may need to store some data about it in the user’s time document, likely storing it based on what day it was completed. I think manual time trackers usually store their data within day of completion.

**Comment by bchehraz** [comment]
@tdepasquale Actually I didn't know subdocuments was a thing! You learn something new everyday. However, with extensibility in mind as Animesh mentioned, separating might be the way to go.

@AnimeshKC you bring up valid points. We'll have to keep brainstorming on how we want to implement goal stats/visualization for the sake of polishing the data schema, even thought we may not work on the feature until Sprint 3+.

**Comment by tdepasquale** [comment]
> Eventually, the user should have the freedom to create a subtask (perhaps mini-task is a better word here) without being assigned to a goal or task. 

I think this could be accomplished through embedding a subdocument like it is now, then also converting the schema to a model to create standalone subtask documents.

> And referencing might also make it easier to change what goal a task or mini-task is part of, as a user may decide that a task belongs to a different goal.

This is true, if we want to have it like Trello where a user can drag and drop subtasks into different task columns or something.

I can change it to refs if everyone agrees it might be better for where we want to take the project in the future. I just modeled it like this because I wasn't sure where we were taking it.

On an unrelated note, we definitely need a better name for subtasks, maybe mini task like Animesh suggested, unless we can come up with something better.

>@tdepasquale Actually I didn't know subdocuments was a thing! You learn something new everyday. However, with extensibility in mind as Animesh mentioned, separating might be the way to go.

haha now you know! I didn't know anything about mongo or mongoose until 2 days ago, just trying to gather as much knowledge about it as I can.

**Comment by tdepasquale** [comment]
Another pattern I've seen is to version the database. So we could add a version variable to the goal schema and default it to the current version number. Then if we update the schema in the future we can run some type of batch command to update all documents in the database with the old version to the new version.

In the interest of time and my lack thereof this week, I'll just reference them like you guys recommend.
